name: Build JAR app of WalkBaBa

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

# defaults:
#   run:
#     working-directory: scripts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup jdk-17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven       
        run: mvn clean package
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: WalkBaba
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: WalkBaba
          
#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{secrets.AZURE_CREDS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'WalkBaba'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp restart --name kikkersANDmonstersB --resource-group finalProject
